version: '3'

networks:
  front-tier:
  back-tier:

services:
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana-conf/provisioning:/etc/grafana/provisioning
      - ./grafana-conf/dashboards:/var/lib/grafana/dashboards
    networks:
      - back-tier
      - front-tier

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 9083:8083
      - 9086:8086
      - 35826:25826/udp
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_DB: telegraf
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: telegraf
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
    networks:
      - back-tier

  telegraf:
    image: telegraf:1.7
    container_name: telegraf
    restart: unless-stopped
    environment:
      INFLUXDB_URI: "http://influxdb:8086"
      INFLUXDB_DB: telegraf
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: telegraf
    volumes:
      - ./telegraf:/var/lib/telegraf
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - back-tier

  prometheus:
    image: prom/prometheus:v2.7.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - back-tier

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command: 
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - back-tier
    restart: always