apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: InfluxDB
    orgId: 2

datasources:
- name: InfluxDB
  type: influxdb
  orgId: 2
  access: proxy
  url: http://influxdb:8086